export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  openaiApiKey: process.env.OPENAI_API_KEY ?? "",
  openaiBaseUrl: process.env.OPENAI_BASE_URL ?? "",
  openaiChatModel: process.env.OPENAI_CHAT_MODEL ?? "gpt-4o",
  openaiWhisperModel: process.env.OPENAI_WHISPER_MODEL ?? "whisper-1",
  gatewayBaseUrl: process.env.GATEWAY_BASE_URL ?? "",
  gatewayApiKey: process.env.GATEWAY_API_KEY ?? "",
};
